### PR TITLE
Use react-router v4

### PR DESCRIPTION
**Pull request by mesaugat**
* Add react-router-dom (v4), remove react-router (v3)
* Fix lint issues and tests
* Add favicon
* Upgrade packages

I think we should not merge this to `master` but create a branch `next` and merge it there. So that we can experiment and master won't be affected. Later on we can merge it altogether.

Let's create a branch `next` and then edit this pull-request to change it's base to `next`.

### CODE REVIEW

**Comment by mesaugat** [comment]
Now we don't have `App.js`, weird.

**Comment by pratishshr** [comment]
Nice.  :+1:
A branch name [next](https://github.com/pratishshr/react-starter/tree/next) has been created.

**Comment by mesaugat** [comment]
Moved base to next.

**Comment by pratishshr** [comment]
👍

**Pull request merged**
